import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AntHeader from "../components/AntHeader";
import AntSider from "../components/AntSider";
import AntContent from "../components/AntContent";
import AntdRegistry from "../components/AntdRegistry";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <AntHeader>
            <ul>
              <li><a href="/spec/database">Database Specification</a></li>
              <li><a href="/spec/log">Log Specification</a></li>
              <li><a href="/spec/middleware">Middleware Specification</a></li>
              <li><a href="/install">Install SDK</a></li>
              <li><a href="/faq">FAQ</a></li>
            </ul>
          </AntHeader>
          <AntSider>Sider content here</AntSider>
          <AntContent>{children}</AntContent>
        </AntdRegistry>
      </body>
    </html>
  );
}
